In [4]:
pip install pandas


SyntaxError: invalid syntax (2344992959.py, line 1)

In [5]:
import pandas as pd

In [7]:
data = pd.read_csv('test.csv')

In [8]:
data

x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
..   ..        ...
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]

In [11]:
X = data['x'].values
X

array([ 77,  21,  22,  20,  36,  15,  62,  95,  20,   5,   4,  19,  96,
        62,  36,  15,  65,  14,  87,  69,  89,  51,  89,  27,  97,  58,
        79,  21,  93,  27,  99,  31,  33,  80,  28,  47,  53,  69,  28,
        33,  91,  71,  50,  76,   4,  37,  70,  68,  40,  35,  94,  88,
        52,  31,  59,   0,  39,  64,  69,  57,  13,  72,  76,  61,  82,
        18,  41,  50,  55,  13,  46,  13,  79,  53,  15,  28,  81,  69,
        52,  84,  68,  27,  56,  48,  40,  39,  82, 100,  59,  43,  67,
        38,  63,  91,  60,  14,  21,  87,  73,  32,   2,  82,  19,  74,
        42,  12,   1,  90,  89,   0,  41,  16,  94,  97,  66,  24,  17,
        90,  13,   0,  64,  96,  98,  12,  41,  47,  78,  20,  89,  29,
        64,  75,  12,  25,  28,  30,  65,  59,  64,  53,  71,  97,  73,
         9,  12,  63,  99,  60,  35,   2,  60,  32,  94,  84,  63,  22,
        81,  93,  33,   7,  42,  46,  54,  16,  49,  43,  95,  66,  21,
        35,  80,  37,  54,  56,   1,  32,  58,  32,  46,  72,  1

In [36]:
Y = data['y'].values
Y

array([ 79.77515201,  23.17727887,  25.60926156,  17.85738813,
        41.84986439,   9.80523488,  58.87465933,  97.61793701,
        18.39512747,   8.74674765,   2.81141583,  17.09537241,
        95.14907176,  61.38800663,  40.24701716,  14.82248589,
        66.95806869,  16.63507984,  90.65513736,  77.22982636,
        92.11906278,  46.91387709,  89.82634442,  21.71380347,
        97.41206981,  57.01631363,  78.31056542,  19.1315097 ,
        93.03483388,  26.59112396,  97.55155344,  31.43524822,
        35.12724777,  78.61042432,  33.07112825,  51.69967172,
        53.62235225,  69.46306072,  27.42497237,  36.34644189,
        95.06140858,  68.16724757,  50.96155532,  78.04237454,
         5.60766487,  36.11334779,  67.2352155 ,  65.01324035,
        38.14753871,  34.31141446,  95.28503937,  87.84749912,
        54.08170635,  31.93063515,  59.61247085,  -1.04011421,
        47.49374765,  62.60089773,  70.9146434 ,  56.14834113,
        14.05572877,  68.11367147,  75.59701346,  59.22

In [2]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [1]:
pip install sklearn

  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2936 sha256=6e57d5965dd9d7ce56d4bf4f0c9d2e1fe3ee921823816ff855d20594a2a418dc
  Stored in directory: c:\users\fg\appdata\local\pip\cache\wheels\f8\e0\3d\9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [14]:
X_train

array([ 50,  14,  13,  31,  91,  20,  39,  71,  87,  97,  21,  12,  45,
        82,  90,  31,  17,  99,  41,  72,  40,   0,  54,  37,  66,  53,
        60,  28,  47,  99,  21,  59,  94,  21,  90,  23,   8,  22,  58,
        46,  22,  24,   9,  32,  64,  23,  16,  20,  15,  27,  48,  72,
        90,  42,  33,  19,  68,  48,  18,  19,  39,  44,   7,  96,  47,
        93,  73,  59,  65,  80,  88,  14,  67,  86,  71,  43,  44,  65,
        79,   1,  97,  78,  77,  55,  56,   2,  36,  78,  37,  73,  53,
        72,  60,  56,  74,  54,  19,  46,  34,  21,   4,  36,  98,  33,
        66,  54,  75,  19,  64,  76,  30,  89,  92,  20,  46,  57,  82,
         4,  23,  81,  91,  12,   6,  55,  84,  27, 100,  41,  27,  77,
        59,  33,  92,  11,  67,  57,  36,  68,  60,  73,  87,  72,  26,
        46,  76,  95,  63,  92,   7,  95,  20,  12,  31,  25,  21,  75,
        74,  35,  68,  13,  28,  38,  52,  46,  62,  59,  95,   8,  28,
        42,  39,  59,  94,   1,  46,  62,  51,  35,  69,  40,  7

In [16]:
from sklearn.linear_model import LinearRegression

In [24]:
model = LinearRegression()

In [27]:
model.fit([X_train], [y_train])

LinearRegression()

In [32]:
Y_pred = model.predict(X_test)

ValueError: Expected 2D array, got 1D array instead:
array=[ 90  76  94   5  91 100   4   0  15  32  16  64  12  37  93 100  61  45
  35  43  52  97  38  21  42  50  25  71  93   5  14  49  80  97  55   0
  95  67  70  53  91  81  16  13  69  61  65  14  16   5  17  12  28  28
  55  58  87  63  77  58  88  57  62   4  56  99  89  89  39  54  89  78
  37  91  29  64  56  40  41  43  16  63  69  41  84  66  13  79  15   4
  61  82  55  96  69  65  72  60  58].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [33]:
Y_pred

NameError: name 'Y_pred' is not defined